name: CI

on:
  # Disabled - superseded by nx-optimized-ci.yml
  # push:
  #   branches:
  #     - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  CI: true
  DEBUG: ''              # empty string disables *everything* that respects DEBUG
  DOTENV_CONFIG_DEBUG: ''# dotenv specifically
  GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
  GSHEETS_SA_KEY: ${{ secrets.GSHEETS_SA_KEY }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: pnpm dlx nx-cloud start-ci-run --distribute-on="6 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Run CI-focused tests (Group 5: Environment/Infrastructure focus)
      # Development tool tests run locally via pre-commit/pre-push hooks
      - name: Run CI tests
        run: pnpm test:ci

      # Build affected projects for deployment
      - run: pnpm exec nx affected -t build --parallel=6
